x-service-templates:
  # Base app service template
  app-base: &app-base
    build:
      context: .
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "140MB"
    expose:
      - "3000"
    volumes:
      - rinha-store:/data
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - DATABASE_PATH=/app/database.sqlite
      - NODE_ENV=production
      - REDIS_HOST=redis
      - RINHA_TOKEN=123
    restart: unless-stopped
    depends_on:
      - payment-processor-1
      - payment-processor-2
      - redis
services:

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - payment-processor
      - backend
    volumes:
      - rinha-store:/data

  app2:
    <<: *app-base
    container_name: app2
    depends_on:
      redis:
        condition: service_healthy

  app1:
    <<: *app-base
    container_name: app1
    depends_on:
      redis:
        condition: service_healthy

  redis:
    hostname: redis
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "40MB"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
    container_name: redis
    volumes:
      - redis_data:/data
    image: redis:alpine
    ports:
      - "6379:6379"

  nginx:
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"
    networks:
      - backend
    image: nginx:stable-alpine
    container_name: nginx-load-balancer
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - app2
#      - app1
    restart: unless-stopped

  mongo-express:
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb # Nome do serviço MongoDB
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
    image: mongo-express
    container_name: mongo-express
    networks:
      - backend # Ambos os serviços precisam estar na mesma rede
    depends_on:
      - mongodb
    ports:
      - "8081:8081"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  redis_data:
  rinha-store:
